name = "DataProfiler"
uuid = "ad453b8f-cafa-432e-8a30-8bb69bbf5e60"
authors = ["Arya Hassibi <arya.hassibi@tu-dortmund.de>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CairoMakie = "0.15.6"
DataFrames = "1"
StatsBase = "0.34"
UnicodePlots = "3"
julia = "^1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
